url: https://lukefretwell.github.io/citycamp-lafayette # the base hostname & protocol for your site, e.g. http://example.com
title: "CityCamp" # the name of your site, e.g. ACME Corp.

# baseurl: "https://citycamp-website-template.citycamp.com" # when deploying to GitHub pages
baseurl: "" # when developing locally

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js


# CityCamp specific variables go below #########################################

city_camp_host_city: "Idealville"
city_camp_organizer_email: "example-organizer@citycamp.com"
city_camp_dark_color: "gray-900" # choose a tailwind color, and set it in .template-colors as well (near the top of index.html)

# Display partners (sponsors) component or not
display_partners: true # true | false
partners:
  - name: "this"
    image_url: "https://citycamp.com/assets/img/posts/default-og.png"
  - name: "that"
    image_url: "https://citycamp.com/assets/img/posts/default-og.png"
